---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "2.3.4"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    configInline: |-
      address-pools:
      - name: default
        protocol: layer2
        addresses:
          - 192.168.77.90-192.168.77.95
      - name: production
        protocol: layer2
        addresses:
          - 192.168.77.100-192.168.77.110