---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - stable.yaml
  - prometheus-community.yaml
  - grafana-community.yaml
  - bitnami.yaml
  - jetstack.yaml
