---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-operator
spec:
  releaseName: jaeger-operator
  chart:
    spec:
      chart: jaeger-operator
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3