---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
spec:
  releaseName: thanos
  chart:
    spec:
      chart: thanos
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3