---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: flux-system
      version: "1.14.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  targetNamespace: flux-system
