---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
spec:
  releaseName: tempo
  chart:
    spec:
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3