---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - gateway.yaml
  - issuer.yaml
  - certificate.yaml
  - alertmanager-vs.yaml
  - prometheus-vs.yaml
  - grafana-vs.yaml
  - tracing-vs.yaml