---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      version: "v1.1.1"
  values:
    installCRDs: true
    extraArgs:
      - --enable-certificate-owner-ref=true
