---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  profile: demo
  meshConfig:
    enablePrometheusMerge: false
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    enableTracing: true
    defaultConfig:
      tracing:
        zipkin:
          address: jaeger-operator-jaeger-collector.observability:9411
        sampling: 50
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            metallb.universe.tf/address-pool: "default"
          service:
            type: LoadBalancer
            loadBalancerIP: 192.168.77.90
    egressGateways:
      - name: istio-egressgateway
        enabled: false