---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-operator
spec:
  values:
    cr:
      create: true
      name: kiali
      namespace: "istio-system"
      spec:
        # https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml
        auth:
          strategy: "anonymous"
        deployment:
          accessible_namespaces:
            - '**'