---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sources
  - ../base/metallb-system
  - ../base/istio-system
  - ../base/cert-manager
  - ../base/kiali-operator
patchesStrategicMerge:
  - metallb-system-values.yaml
  - istio-system-values.yaml
  - kiali-operator-values.yaml
