---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - ../base/kube-prometheus-stack
  - ../base/thanos
  - ../base/loki-stack
#  - ../base/tempo
  - ../base/jaeger-operator
patchesStrategicMerge:
  - kube-prometheus-stack-values.yaml
  - thanos-values.yaml
  - loki-stack-values.yaml
#  - tempo-values.yaml
  - jaeger-operator-values.yaml
