---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - ../base/kube-prometheus-stack
  - ../base/loki-stack
patchesStrategicMerge:
  - kube-prometheus-stack-values.yaml
