---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
spec:
  chart:
    spec:
      version: ">=2.3.0"
  values:
    loki:
      enabled: true
      replicas: 1
      serviceMonitor:
        enabled: true
        interval: 15s
        additionalLabels:
          tier: cluster
    promtail:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 15s
        additionalLabels:
          tier: cluster
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
