---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
spec:
  chart:
    spec:
      version: ">=0.4.0"
  values:
    query:
      enabled: true
      replicaLabels:
        - prometheus_replica
      stores:
        - "--store=dnssrv+_grpc._tcp.kube-prometheus-stack-thanos-discovery.observability.svc.cluster.local"
      metrics:
        serviceMonitor:
          enabled: true
          labels:
            tier: cluster
    store:
      enabled: false
    compact:
      enabled: false
    bucket:
      enabled: false
    rule:
      enabled: false
    sidecar:
      enabled: false
